# Generated by Django 4.1.4 on 2022-12-26 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='aprobado',
            fields=[
                ('aprobado_id', models.AutoField(primary_key=True, serialize=False, verbose_name='aprobado_id')),
                ('descripcion', models.CharField(max_length=20, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='carrusel',
            fields=[
                ('id_carrusel', models.AutoField(primary_key=True, serialize=False, verbose_name='id_carrusel')),
                ('imagen_carrusel', models.ImageField(null=True, upload_to='carrusel')),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False, verbose_name='categoria_id')),
                ('descripcion', models.CharField(max_length=20, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='envio',
            fields=[
                ('envio_id', models.AutoField(primary_key=True, serialize=False, verbose_name='envio_id')),
                ('descripcion', models.CharField(max_length=20, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='estado_producto',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False, verbose_name='estado_id')),
                ('descripcion', models.CharField(max_length=20, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('titulo', models.CharField(max_length=30, verbose_name='titulo')),
                ('descripcion', models.TextField(max_length=255, verbose_name='descripcion')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('aprobado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.aprobado')),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.categoria')),
                ('envio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.envio')),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.estado_producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
