# Generated by Django 4.1.4 on 2022-12-26 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0002_alter_producto_aprobado_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagenCarrusel',
        ),
    ]
