# Generated by Django 4.1.4 on 2022-12-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0003_delete_imagencarrusel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrusel',
            name='imagen_carrusel2',
            field=models.ImageField(null=True, upload_to='carrusel'),
        ),
        migrations.AddField(
            model_name='carrusel',
            name='imagen_carrusel3',
            field=models.ImageField(null=True, upload_to='carrusel'),
        ),
    ]
